### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Januek** [nccgroup/ghostrings#1]
Selected file is not a valid Ghidra Extension
---------------------------------------------------
Build Date: 2022-Nov-15 1249 EST
Ghidra Version: 10.2.2
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot
JVM Version: Eclipse Adoptium 17.0.6
OS: Windows 10 10.0 amd64

**Comment by jamchamb** [comment]
Hello, which build did you try? It looks like it might have been the source code zip instead of a build like <https://github.com/nccgroup/ghostrings/releases/download/v2.0/ghidra_10.2.2_PUBLIC_20230124_Ghostrings.zip>.
