### ISSUE TITLE
Installation Error Ghidra 10.3.1

### ISSUE THREAD

**Issue by Compr0mzd** [nccgroup/ghostrings#2]
Extension version for [ghidra_10.3_PUBLIC_20230524_Ghostrings.zip] is incompatible with Ghidra.
---------------------------------------------------
Build Date: 2023-Jun-14 1629 EDT
Ghidra Version: 10.3.1
Java Home: C:\Program Files\OpenJDK\jdk-20.0.1
JVM Version: Oracle Corporation 20.0.1
OS: Windows 10 10.0 amd64
Workstation: DESKTOP

**Comment by jamchamb** [comment]
Please try with [ghidra_10.3.1_PUBLIC_20230711_Ghostrings.zip](https://github.com/nccgroup/ghostrings/releases/download/v2.1/ghidra_10.3.1_PUBLIC_20230711_Ghostrings.zip)
